import type { ViteUserConfig } from 'astro'
import type { ResolvedConfig } from '../config'

export function vitePluginAstroFridayUnoCSSExtract(resolvedConfig: ResolvedConfig) {
  const virtualModuleId = 'virtual:astro-friday-unocss-extract'
  const resolvedVirtualModuleId = `\0${virtualModuleId}`

  return {
    name: 'vite-plugin-astro-friday-unocss-extract',
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },
    load(id) {
      if (id === resolvedVirtualModuleId) {
        return /* js */`
          // This file is auto generated by astro-friday
          // since \`.js\` files are not included by default,
          // the following comment tells UnoCSS to force scan this file.
          // @unocss-include
          // @see https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline
          export default [
            // icons from navigations
            \`${Object.values(resolvedConfig.navigations).map(i => i.icon).filter(Boolean).join(' ')}\`,
          ]
        `
      }
    },
  } satisfies NonNullable<ViteUserConfig['plugins']>[number]
}
